const { moddedUnits } = require("../getModdedContent.js");

module.exports = {
  // Vanilla units
  vanilla: {
    MACE: "mace",
    DAGGER: "dagger",
    CRAWLER: "crawler",
    FORTRESS: "fortress",
    SCEPTER: "scepter",
    REIGN: "reign",
    VELA: "vela",
    NOVA: "nova",
    PULSAR: "pulsar",
    QUASAR: "quasar",
    CORVUS: "corvus",
    ATRAX: "atrax",
    SPIROCT: "spiroct",
    ARKYID: "arkyid",
    TOXOPID: "toxopid",
    FLARE: "flare",
    ECLIPSE: "ecplise",
    HORIZON: "horizon",
    ZENITH: "zenith",
    ANTUMBRA: "antumbra",
    MONO: "mono",
    POLY: "poly",
    MEGA: "mega",
    QUAD: "quad",
    OCT: "oct",
    ALPHA: "alpha",
    BETA: "beta",
    GAMMA: "gamma",
    RISSO: "risso",
    MINKE: "minke",
    BRYDE: "bryde",
    SEI: "sei",
    OMURA: "omura",
    RETUSA: "retusa",
    OXYNOE: "oxynoe",
    CYERCE: "cyerce",
    AEGIRES: "aegires",
    NAVANAX: "navanax",
  },

  // Modded units
  mod: moddedUnits,
};
